HTCONDOR-1484 fix for eval crash by adding to_delete ptrs to EvalState
htcondor/htcondor pull request #1041
Opened 2022-12-14 17:52 UTC by johnkn

and modifying EvaluateExpr and EvaluateAttr to convert results to self-contained by default. This changes the classad ABI, so the SOVERSION is updated to 16

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2022-12-16 01:23 UTC, timtheisen commented
This change is insufficient. Corresponding packaging changes need to be done. Maybe we can remove all the SOVERSION stuff since we we really do not want to support a standalone ClassAd library.

2022-12-20 16:44 UTC, JaimeFrey requested changes
All notes are inline.

2022-12-20 16:44 UTC, JaimeFrey commented on src/classad/exprTree.cpp
> +bool EvalState::GivePtrToValue(Value & val)
This feels like it should just be in the body of Value::MakeSelfContained(). Then, Value doesn't have to make EvalState a friend.

2022-12-20 16:46 UTC, JaimeFrey commented
I don't see any mention of the ClassAds library SO version in the files under build/packaging/, just wildcards on the library filename.

2022-12-20 16:53 UTC, johnkn commented on src/classad/exprTree.cpp
> +		cache_to_delete.erase(last, cache_to_delete.end());
This code is from Greg.  remove guarantees that the iterator points to the first of the elements to be removed, or to the first element after the end if it is not found.

2022-12-20 17:04 UTC, JaimeFrey commented on src/classad/exprTree.cpp
> +		cache_to_delete.erase(last, cache_to_delete.end());
The two-argument call to erase() you have removes the matching element and all elements after it. We only want to erase the single element, which is what the single-argument form does.

2022-12-20 17:20 UTC, JaimeFrey commented on src/classad/exprTree.cpp
> +		cache_to_delete.erase(last, cache_to_delete.end());
Oops. I missed that the preceding call is a std::remove(), and not a find() like in the other function. I retract my suggestion.

2022-12-20 19:15 UTC, JaimeFrey approved these changes
Looks good now.

2022-12-20 19:23 UTC, merged