Record server's X509 certificate for the client. HTCONDOR-43
htcondor/htcondor pull request #145
Opened 2020-12-20 17:02 UTC by bbockelm

This records the observed X509 certificate from the server and puts it in the client's session.  With this, we can return the information to the invoking user for condor ping.

We are interested in the public cert so OSG can better debug authentication failures (and understand how widely a CA is used, for example) and allow sites to easily remotely monitor the certificate's expiration time.

@brianhlin 

Fixes: HTCONDOR-43

2020-12-21 20:43 UTC, JaimeFrey requested changes

2020-12-21 20:43 UTC, JaimeFrey commented on src/condor_io/condor_auth_ssl.cpp
> +			ad.InsertAttr("ServerPublicCert", pem_raw, len);
The attribute name should be added to condor_attributes.h and the macro used here.

2020-12-21 20:43 UTC, JaimeFrey commented on src/condor_io/condor_auth_x509.cpp
> +			ad.InsertAttr("ServerPublicCert", cred);
The attribute name should be added to condor_attributes.h and the macro used here.

2021-01-04 21:22 UTC, timtheisen commented
@JaimeFrey will make the recommended changes.

2021-01-05 17:16 UTC, JaimeFrey approved these changes

2021-01-05 17:40 UTC, merged