Remove the JSON from the local issued token
htcondor/htcondor pull request #162
Opened 2021-03-26 13:42 UTC by djw8605

JSON in the token file is not a supported feature of the WLCG
token discovery proposal.  Further, every tool so far written
simply extracts the access_key from the json, without looking
at the expires attribute.

2021-03-26 14:04 UTC, jasoncpatton requested changes
LGTM except making sure a changed var name is used later. Will poke around to make sure no one is depending on JSON and will add version history so that this doesn't blindside anyone.

2021-03-26 14:32 UTC, jasoncpatton commented
@djw8605 Would you mind refactoring your change to depend on a condor config knob instead? (You can choose the name but as a suggestion `LOCAL_CREDMON_ACCESS_TOKEN_USE_JSON`.) If you don't have time right now, I can do it but probably not before later next week.

2021-04-06 16:40 UTC, djw8605 commented
@jasoncpatton I think we can wait for you to come back and merge this.  Thanks for this!

2021-04-16 12:00 UTC, jasoncpatton requested changes

2021-04-16 13:53 UTC, djw8605 commented
All looks good to me.

2021-04-16 22:30 UTC, merged