HTCONDOR-1994 daemon
htcondor/htcondor pull request #1766
Opened 2023-09-12 20:17 UTC by JaimeFrey

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2023-09-13 19:57 UTC, GregThain requested changes

2023-09-13 20:18 UTC, JaimeFrey commented on src/condor_daemon_client/daemon.cpp
> +			 _full_hostname.c_str(),
Oops, will fix.

2023-09-13 20:21 UTC, JaimeFrey commented on src/condor_daemon_client/daemon.h
> +	std::string _subsys;
The end of the struct has private members, and these are protected (one is referenced by a child class). There are 6 bools, so we wouldn't get any space savings at present.

2023-09-13 20:21 UTC, JaimeFrey commented on src/condor_daemon_client/daemon.h
> +	std::string _subsys;
I did move _cmd_str, which was hidden amongst member functions.

2023-09-14 17:43 UTC, GregThain approved these changes
LGTM.

2023-09-14 17:43 UTC, merged