Provide capabilities for remote administration
htcondor/htcondor pull request #184
Opened 2021-05-23 23:10 UTC by bbockelm

This PR provides a mechanism for remote administration (`condor_on`, `condor_off`, `condor_fetch_log`, ...) of a daemon based on capabilities advertised by that daemon to the collector.

DaemonCore generates a session that is generous enough for basic administration - and the collector will only forward this session information for sessions that have administrator privilege.

The Daemon client class will automatically pick up the session information, if present, and install it.  This means any corresponding tool will utilize it.

To get a new, clean private attribute that's not otherwise used, this introduces the `_condor_Priv` prefix; anything with this prefix is automatically considered a private attribute.  There is some tricky code that ensures any such prefix is only sent to a remote side if the remote is of a sufficient version (this prevents an older daemon from accidentally leaking the attribute because it doesn't understand the prefix).

2021-09-02 21:39 UTC, JaimeFrey requested changes
Comments not tied to specific lines of code:
* The new attribute _condor_PrivRemoteAdmin is vulnerable to the exploit in HTCONDOR-587.
* How does a client that wants to use the remote admin capability opt into stricter authentication constraints when doing a READ-level query to the collector?
* The collector ad will not have a remote admin capability. This is an inconsistency we should try to avoid.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_io/condor_secman.cpp
> +		if (!strcmp(sock.getAuthenticationMethodUsed(), potential_method)) {
This needs to be a case-insensitive comparison.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_collector.V6/collector.cpp
> +	if (verinfo && verinfo->built_since_version(9, 1, 1) &&
This version check should be the version this code is being merge into for release.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_daemon_client/daemon.cpp
> +		dprintf(D_FULLDEBUG, "Creating a new administrative session for capability %s\n", capability.c_str());
This dprintf() leaks the secret part of the capability. Use ClaimIdParser::publicClaimId() to print just the non-secret portion.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_daemon_core.V6/condor_daemon_core.h
> +	time_t m_remote_admin_last_time{0};
m_remote_admin_last_time is never set to anything other than 0.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_daemon_core.V6/condor_daemon_core.h
> +	static time_t m_startup_time;
I'd like to see this new startup timestamp tied or unified with the startup timestamp DCCollector::startTime. Probably by setting DCCollector::startTime to match DaemonCore::m_startup_time. Also, change DaemonCore::getStartTime() to use DaemonCore::m_startup_time.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_daemon_core.V6/daemon_core.cpp
> +		capability = id + "#" + session_info + keybuf.get();
Use ClaimIdParser::claimId() to construct the final capability string.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_daemon_core.V6/daemon_core.cpp
> +	m_remote_admin_last = retval;
m_remote_admin_last should be assigned from capability, not retval.

2021-09-02 21:39 UTC, JaimeFrey commented on src/condor_daemon_core.V6/daemon_core.cpp
> +	formatstr( id, "%s#%ld#%lu", daemonCore->publicNetworkIpAddr(),
These session ids collide with the ones the startd constructs for match claiming. They need to be altered to be unique.

2021-09-09 17:57 UTC, bbockelm commented
@JaimeFrey - thanks for the review!  Seems a good couple finds.  Hope to work on it this weekend.  For your non-specific items:

> The new attribute _condor_PrivRemoteAdmin is vulnerable to the exploit in HTCONDOR-587.

Yup - obviously this code all came from before that.  Will look into using a similar approach.

> How does a client that wants to use the remote admin capability opt into stricter authentication constraints when doing a READ-level query to the collector?

Currently, you can't.  So, if you have the (non-default) setting where `READ` doesn't require integrity and `ADMINISTRATOR` does, then you don't get the remote capabilities and you have the same situation as today: the client won't get a session created internally and will force a new authentication once it talks to the remote daemon.

Since we don't know a priori whether remote administration is a possibility, I'd be reluctant to force ADMINISTRATOR-level authentication when READ might suffice.

Another possibility is a fallback -- talk to the collector, authenticate with the daemon (fail), and then talk to the collector again with a different authentication setting.  However, that's a much wider-ranging change.

Hence, the current compromise in the code: do a best effort (which should work with out-of-the-box settings of HTCondor) and fallback to existing authentication methods.  Is that workable?

> The collector ad will not have a remote admin capability. This is an inconsistency we should try to avoid.

Agreed, consistency is good.  Will look into it.

Are you thinking of a particular use case though?  I guess I had assumed that if you have ADMINISTRATOR authorization on the collector then you don't need the capabilities in the collector ad.



Finally -- something not in the code review but obvious on re-reading this.  Should we cowardly refuse to send the capabilities on a connection that isn't encrypted?

2021-10-30 17:38 UTC, bbockelm commented
@JaimeFrey - ready for review!
- The various code-level comments were addressed.
- The collector now encrypts all in-memory private attributes (only decrypting them as it's putting them on the wire), preventing various in-memory leaks of the secrets.
- The collector ad itself also gets the administrative capability.

2021-12-09 04:17 UTC, JaimeFrey requested changes
The changes in _putClassAd() will conflict with HTCONDOR-730. We will have to plan how to resolve that.
Other change requests are inline.

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_collector.V6/collector.cpp
> +	if (verinfo && verinfo->built_since_version(9, 4, 0) &&
This will need to be changed to the merged-to version.

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +	bool exclude_private_v2 = exclude_private || !verinfo || !verinfo->built_since_version(9, 1, 1);
This will need to be changed to the merged-to version.

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +	bool exclude_private_v2 = exclude_private || !verinfo || !verinfo->built_since_version(9, 1, 1);
This will need to be changed to the merged-to version.

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +				is_private_attr = true;
is_private_attr must already be true here.

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +			is_private_attr = true;
is_private_attr must already be true here.

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +		bool is_private_attr = ClassAdAttributeIsPrivateV2(*attr);
```suggestion
		bool is_private_attr = ClassAdAttributeIsPrivateAny(*attr);
```

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_utils/memory_seal.cpp
> +	std::unique_ptr<unsigned char, decltype(&free)> new_key(
I don't believe the hkdf() call is necessary here, not that it harms anything.

2021-12-09 04:17 UTC, JaimeFrey commented on src/condor_utils/memory_seal.cpp
> +	output_data.resize((((input_data_len + IV_LEN + 2) / 3) << 2));
This should be a reserve(). The size and contents of the string are overwritten unconditionally later.
```suggestion
	output_data.reserve((((input_data_len + IV_LEN + 2) / 3) << 2));
```

2022-02-28 19:11 UTC, JaimeFrey reviewed
Add comment about unnecessary hkdf() call.

2022-02-28 19:11 UTC, JaimeFrey commented on src/condor_utils/memory_seal.cpp
> +	std::unique_ptr<unsigned char, decltype(&free)> new_key(
```suggestion
	// I don't believe the hkdf() call here is necessary, as the input
	// key material should already be uniformly random and the size we
	// need. The call doesn't do any harm, but may slow things down.
	//   - Jaime Frey
	std::unique_ptr<unsigned char, decltype(&free)> new_key(
```

2022-03-18 14:40 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +			is_private_attr = true;
Resolved with merge from master.

2022-03-18 14:53 UTC, JaimeFrey reviewed
Fix typos in resolving merge conflict. HTCONDOR-1010

2022-03-18 14:53 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +			if (crypto_is_noop && !exclude_private && !exclude_prviate_v2 && !g_encryptPrivateAttrs) {
```suggestion
			if (crypto_is_noop && !exclude_private && !exclude_private_v2 && !g_encryptPrivateAttrs) {
```

2022-03-18 14:53 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +				bool private_attr_v2 = ClassAdAttributeIsPrivateV2(attr));
```suggestion
				bool private_attr_v2 = ClassAdAttributeIsPrivateV2(attr);
```

2022-03-18 14:53 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +			if ((crypto_is_noop && !exclude_private && !exclude_prviate_v2 && !g_encryptPrivateAttrs) || (private_count == 0)) {
```suggestion
			if ((crypto_is_noop && !exclude_private && !exclude_private_v2 && !g_encryptPrivateAttrs) || (private_count == 0)) {
```

2022-03-18 14:53 UTC, JaimeFrey commented on src/condor_utils/classad_oldnew.cpp
> +        bool private_attr_v2 = ClassAdAttributeIsPrivateV2(attr));
```suggestion
				bool private_attr_v2 = ClassAdAttributeIsPrivateV2(attr);
```

2022-03-18 16:56 UTC, JaimeFrey approved these changes
There are a couple problems with the memory sealing use:
* The collector reads a sealed value without decrypting it.
* Doing the sealing process-wide may cause problems (e.g. CCB sends/receives ads with a ClaimId attribute).
I will merge this code into a new topic branch in the main repo, address these issues there, then merge that into master in a new PR.

2022-03-18 16:56 UTC, merged