V23_2-HTCONDOR-2114-periodic-vacate
htcondor/htcondor pull request #1867
Opened 2023-10-24 17:40 UTC by GregThain

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2023-10-25 16:44 UTC, GregThain commented
```mermaid
.. mermaid::
   :caption: Machine states and the possible transitions between the states
   :align: center

   stateDiagram-v2
     direction LR
     [*]--> Owner
     Owner --> Unclaimed: A
     Unclaimed --> Matched: C
     Unclaimed --> Owner: B
     Unclaimed --> Drained: P
     Unclaimed --> Backfill: E
     Unclaimed --> Claimed: D
     Backfill  --> Owner: K
     Backfill  --> Matched: L
     Backfill  --> Claimed: M
     Matched --> Claimed: G
     Matched --> Owner: F
     Claimed --> Preempting: H
     Preempting --> Owner: J
     Preempting --> Claimed: I
     Owner --> Drained: N
     Drained --> Owner: O

```

2023-10-26 16:30 UTC, JaimeFrey requested changes
The periodic vacate is evaluated at on-exit time (like the other periodic exprs are). Do we want that and if so, what should it mean?
The schedd, job router, and gridmanager evaluate job policy. They need to updated to handle VACATE_FROM_RUNNING. The job router and gridmanager can't vacate a running job, so we need to decide what they will do.
For Condor-C jobs, the gridmanager removes all of the policy attributes for the downstream job it submits. Should it do the same for vacate?

2023-10-27 16:16 UTC, JaimeFrey requested changes
The job router's policy evaluation still needs updating.

2023-10-27 16:16 UTC, JaimeFrey commented on src/condor_utils/user_job_policy.cpp
> +		if ((mode == PERIODIC_ONLY) && ((state == RUNNING) || (state == SUSPENDED))) {
The check of state is redundant here with the enclosing if().

2023-11-01 19:09 UTC, JaimeFrey requested changes

2023-11-01 19:09 UTC, JaimeFrey commented on src/condor_job_router/JobRouter.cpp
> +			SetJobIdle(job);
SetJobIdle() just sets the JobStatus of the source job to Idle. I think the Job Router should treat VACATE_FROM_RUNNING the same as STAYS_IN_QUEUE (i.e. do nothing). The job policy expressions are forwarded to the routed job, where PeriodicVacate can have its intended effect. Evaluating the policy expressions in both the unrouted and routed jobs is highly suspect to me, but that's an issue for another ticket.

2023-11-01 20:07 UTC, JaimeFrey approved these changes
LGTM

2023-11-01 21:05 UTC, merged