HTCONDOR-2200  First pass at an FAQ/recipe/example section.
htcondor/htcondor pull request #2192
Opened 2024-02-14 22:39 UTC by Todd-L-Miller

In contrast to GregT's effort (#2165).

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2024-02-16 20:48 UTC, GregThain requested changes

2024-02-16 20:48 UTC, GregThain commented on docs/faq/admins/breadth-first.rst
> +HTCondor uses static slots by default.
Not anymore....

2024-02-21 22:34 UTC, Todd-L-Miller commented on docs/faq/admins/breadth-first.rst
> +HTCondor uses static slots by default.
Section updates, rereview requested.

2024-02-22 16:52 UTC, GregThain approved these changes
LGTM.

2024-02-22 16:52 UTC, merged