HTCONDOR-2335 convert-string-lists
htcondor/htcondor pull request #2298
Opened 2024-03-13 15:11 UTC by JaimeFrey

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2024-03-13 16:02 UTC, GregThain commented on src/condor_utils/compat_classad.cpp
> +		int r = sscanf(entry.c_str(), "%lf", &temp);
Not all our compilers support this yet, but at some point, we should replace these sscanf's with the double overload of `std::from_chars`, which is faster, avoids all format-string security and varags wonkiness.

2024-03-22 14:14 UTC, GregThain requested changes

2024-03-22 14:37 UTC, JaimeFrey commented on src/condor_utils/compat_classad.cpp
> +		if (strspn(entry.c_str(), "+-0123456789") != strlen(entry.c_str())) {
Done

2024-03-22 14:37 UTC, JaimeFrey commented on src/condor_utils/compat_classad.cpp
> +	}
Done

2024-03-22 15:49 UTC, GregThain approved these changes
LGTM.

2024-03-22 15:50 UTC, merged