HTCONDOR-2364 Non-blocking removal of child jobs from a dag removal
htcondor/htcondor pull request #2354
Opened 2024-04-01 14:21 UTC by GregThain

Enqueue up the child job removals into a self-draining queue.

These removals happen in separate transactions than the original removal, which is no more broken than the original code, which removed them in one big separate transaction from the original transaction.

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2024-04-01 16:23 UTC, GregThain commented
Ugh.  Note the suspiciously-related test failure `job_dagman_fullremove` on the slower platforms...

2024-04-03 16:45 UTC, JaimeFrey requested changes
abortJobsByConstraint() is now unused, and can be deleted.
For nested DAGs, either removeOtherJobs() needs to call itself recursively on the child jobs or mark_idle() needs to call scheduler.enqueueActOnJobMyself() on REMOVED jobs instead of doing the log writing and DestroyProc() itself.

2024-04-04 21:09 UTC, JaimeFrey commented
It looks like we need a call to scheduler.enqueueActOnJobMyself() on startup for HTCONDOR-186 as well.

2024-04-10 14:07 UTC, GregThain commented
Let's try another approach, in another PR.

2024-04-10 14:23 UTC, closed without merging