Implement htcondor2.set_ready_state()
htcondor/htcondor pull request #2755
Opened 2024-09-05 21:59 UTC by Todd-L-Miller

If we want to test without version 1 of the Python bindings at all, we have some more work to do.

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2024-09-10 17:34 UTC, JaimeFrey requested changes
This is not how you get the family security session. It's passed in a separate environment variable (CONDOR_PRIVATE_INHERIT). See get_family_session() in src/python-bindings/dc_tool.cpp.

2024-09-10 20:57 UTC, Todd-L-Miller commented
Yeah.  I honestly don't know what I was thinking there, or why it pretended to work,  Any thoughts on `getSecMan()`?

2024-09-16 16:24 UTC, Todd-L-Miller commented on src/condor_daemon_client/daemon.h
> +
Not now that we've given up on family security, anyway.  Removed.

2024-09-17 19:27 UTC, JaimeFrey approved these changes
LGTM

2024-09-17 19:28 UTC, merged