HTCONDOR-2672 64 bit time_t
htcondor/htcondor pull request #2877
Opened 2024-10-18 15:02 UTC by GregThain

<Insert PR description here, and leave checklist below for code review.>

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed  (documentation [build logs](https://readthedocs.org/projects/htcondor/builds/))
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that each commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2024-10-18 16:00 UTC, JaimeFrey requested changes
TimerManager::ResetTimer() isn't prepared for either `when` or `period` to be TIMER_NEVER that's not the old INT_MAX-ish value.

2024-10-18 16:00 UTC, JaimeFrey commented on src/condor_utils/cron_job_params.cpp
> +		int		num = sscanf( param_period.c_str(), "%ld%c",
time_t is a long long on Windows. I think you need to store the value in a local long long variable, then assign into m_period after the sscanf().

2024-10-18 16:00 UTC, JaimeFrey commented on src/condor_daemon_core.V6/condor_timer_manager.h
> +const time_t TIME_T_NEVER	= -1;
```suggestion
const time_t TIMER_NEVER	 = std::numeric_limits<time_t>::max();
const time_t TIME_T_NEVER	= std::numeric_limits<time_t>::max();
```
These need to be positive values.

2024-10-18 22:24 UTC, GregThain commented
@JaimeFrey changes look good to me, and a new coverity run shows no new problems.

2024-10-21 14:57 UTC, JaimeFrey approved these changes
LGTM

2024-10-21 16:17 UTC, merged