HTCONDOR-838 import blahp
htcondor/htcondor pull request #332
Opened 2021-11-29 20:52 UTC by JaimeFrey

Import blahp code-base into HTCondor repository.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-838

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2021-11-30 22:04 UTC, timtheisen commented
@matyasselmeci Since the condor-blahp RPM will replace the blahp RPM. Do we need a Conflcts: and/or Obsoletes:
Let us know.

2021-12-01 00:02 UTC, matyasselmeci commented
Yes, if this is going into condor 9.5.0, you should do:
```
Provides: blahp = %{version}-%{release}
Obsoletes: blahp < 9.5.0
```
Conflicts aren't necessary.

2021-12-01 17:16 UTC, timtheisen requested changes
In the Debian control files. the htcondor package need the following additional declarations:
Provides: blahp
Conflicts: blahp
Replaces: blahp

You'll have to add them to the existing declarations for Conflicts and Replaces.

2021-12-01 17:16 UTC, timtheisen commented on build/packaging/srpm/condor.spec
> +
Need to say that condor-blahp replaces blahp
```suggestion
Provides: blahp = %{version}-%{release}
Obsoletes: blahp < 9.5.0

```

2021-12-03 23:20 UTC, timtheisen approved these changes
Looks good now.

2021-12-04 04:29 UTC, merged