HTCONDOR-996 job submit method recording branch
htcondor/htcondor pull request #498
Opened 2022-03-23 18:14 UTC by ColeBollig

This is code to implement the JobSubmitMethod Job ad attribute. The new code: overrides the submit hash init(), sets the value at various parts in the code, allows for output display similar to Job status during condor_q --help, added an ornithology test, and documents the features.
Extra checks:
-[ ] Verify documentation looks right (job-classad-attributes.rst & schedd.cpp)
-[ ] Verify my test call is correct in the cmake file
Messed up branch naming. Is a new feature should be V9_8 not V9_0

############################################################################################

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2022-03-23 18:36 UTC, johnkn commented on src/condor_q.V6/queue.cpp
> +		printf("\t%3s %s\n", "UND", getSubmitMethodString(submit_method::UNDEFINED));
prefer not to have a defined undefined value

2022-03-23 18:41 UTC, johnkn commented on src/condor_tools/htcondor_cli/dagman.py
> +        submit_description.setSubmitMethod(5)
can we get the constant from the bindings here, instead of hard-coding a number?

2022-03-23 18:42 UTC, johnkn commented on src/condor_tools/htcondor_cli/job.py
> +            submit_description.setSubmitMethod(3)
get constant from the bindings?

2022-03-23 18:44 UTC, johnkn commented on src/condor_utils/submit_utils.cpp
> +	SubmitMacroSet.sources.push_back("<Argument>");
why does this show up in git as new code?

2022-03-23 18:47 UTC, ColeBollig commented
That is because I copied and pasted the init() to overload it with the submit method value. Thinking back now, is it possible just to have the overload call the original within to not have rewritten lines?
________________________________
From: John (TJ) Knoeller ***@***.***>
Sent: Wednesday, March 23, 2022 1:44 PM
To: htcondor/htcondor ***@***.***>
Cc: Cole Bollig ***@***.***>; Author ***@***.***>
Subject: Re: [htcondor/htcondor] HTCONDOR-996 job submit method recording branch (PR #498)


@johnkn commented on this pull request.

________________________________

In src/condor_utils/submit_utils.cpp<https://github.com/htcondor/htcondor/pull/498#discussion_r833609803>:

> @@ -1165,6 +1167,24 @@ void SubmitHash::init()
        mctx.cwd = NULL;
 }

+//init() overload for assigning JobSubmitMethod to init passed value as enum
+void SubmitHash::init(submit_method value)
+{
+       clear();
+       SubmitMacroSet.sources.push_back("<Detected>");
+       SubmitMacroSet.sources.push_back("<Default>");
+       SubmitMacroSet.sources.push_back("<Argument>");


why does this show up in git as new code?

—
Reply to this email directly, view it on GitHub<https://github.com/htcondor/htcondor/pull/498#pullrequestreview-919280097>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AL5V44G47CCK5QSHGETRQG3VBNRCTANCNFSM5ROYHZYA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-03-23 18:51 UTC, johnkn commented on src/condor_utils/submit_utils.h
> +	void setSubmitMethod(int value){ s_method = (value < -1 || value > 6) ? submit_method::UNDEFINED : static_cast<submit_method>(value); }
remove the range check here,  either allow any value or change the type to the enum type instead of int

2022-03-28 20:55 UTC, johnkn requested changes

2022-03-28 20:55 UTC, johnkn commented on src/condor_includes/proc.h
> +#define JOB_SUBMIT_METHOD_MAX 100
give these a common prefix like METH_ or JSM_ to help avoid unexpected expansion of these macros in code that does not intend it.  bare DAGMAN seems particularly dangerous.

2022-03-28 20:55 UTC, johnkn commented on src/condor_tools/htcondor_cli/dagman.py
> +CONST_SUBMIT_METHOD = 4
rename this to match the enum #define for this tool

2022-03-28 20:55 UTC, johnkn commented on src/condor_utils/submit_utils.cpp
> +}
don't need two init() functions, just use a default argument.

2022-03-28 20:55 UTC, johnkn commented on src/condor_utils/submit_utils.h
> +	void init(int value);
no need for a second init() function, use a default argument

2022-03-28 20:55 UTC, johnkn commented on src/python-bindings/schedd.cpp
> +        .def("getSubmitMethod", &Submit::getSubmitMethod,
I want Jason to look at this and approve the strategy of having an unducumented internal method for CLI

2022-03-29 19:42 UTC, johnkn requested changes

2022-03-29 19:42 UTC, johnkn commented on src/python-bindings/schedd.cpp
> +		if ( method_value < JSM_USER_SET && !allow_reserved_values) {
negative values should not throw

2022-03-29 20:55 UTC, johnkn approved these changes
Looks good.

2022-03-29 22:18 UTC, merged