HTCONDOR-1087 - V9_9-HTCONDOR-1087-pcre2
htcondor/htcondor pull request #568
Opened 2022-04-28 19:16 UTC by GregThain

https://opensciencegrid.atlassian.net/browse/HTCONDOR-1087

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2022-05-05 19:34 UTC, JaimeFrey requested changes
In regexp_helper(), make the following changes:
* Change the type of 'options' and remove 'options_pcre2'
* Change the type of 'target_idx' and remove casts
* Remove the cast when freeing groups_pcre2

2022-05-05 21:54 UTC, GregThain commented
I don't know that there's a clean solution for the `pcre2_substring_list_free` cast -- it takes a `PCRE2_SPTR *`, but `pcre2_substring_list_get` takes a PCRE2_UCHAR ***, and returns in it a list of matches in one allocated block that pcre2_substring_list_free returns: https://www.pcre.org/current/doc/html/pcre2_substring_list_get.html

2022-05-05 21:58 UTC, JaimeFrey commented
I haven't looked at the actual header files, but PCRE2_SPTR and PCRE2_UCHAR  aren't unsigned char* and unsigned char? That sounds like a bad API if it requires casting.

2022-05-06 14:50 UTC, JaimeFrey commented
Ugh. PCRE2_SPTR is const unsigned char*. So without the explicit cast, the pcre2_substring_list_free() requires an implicit cast from unsigned char** to const unsigned char**, which can violate const protection in the general case.

2022-05-06 14:52 UTC, JaimeFrey approved these changes
LGTM

2022-05-13 20:30 UTC, JaimeFrey requested changes
Remove old commented-out code.
Otherwise, looks good.

2022-05-13 20:30 UTC, JaimeFrey commented on src/condor_starter.V6.1/starter.cpp
> +			//int * ovector = (int *) malloc(ovecsize * sizeof(int));
```suggestion
```

2022-05-13 20:30 UTC, JaimeFrey commented on src/condor_starter.V6.1/starter.cpp
> +				//int status = pcre_exec(re, NULL, resid, cchresid, 0, 0, ovector, ovecsize);
```suggestion
```

2022-05-13 20:30 UTC, JaimeFrey commented on src/condor_starter.V6.1/starter.cpp
> +			//free(ovector);
```suggestion
```

2022-05-13 21:04 UTC, JaimeFrey commented
Does this merit a mention in the version history?

2022-05-16 12:54 UTC, JaimeFrey approved these changes
I should make sure to hit the "Approve" radio button when I approve a PR.

2022-05-16 16:07 UTC, merged