HTCONDOR-692:  Utilize user-provided hostname, not canonical name, for alias.
htcondor/htcondor pull request #584
Opened 2022-05-06 21:42 UTC by Todd-L-Miller

See #572; this PR just adds the sugggested release note and corrects a typo in the original commit message.

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2022-05-06 21:45 UTC, Todd-L-Miller commented
From #572:

> I can't speak to the security implications of the change, but the code is fine and the change seems sane.
>
> This could break currently-functioning SSL set-ups if the cert in use includes only the ANAME and not the CNAME (as a
> SAN). I'll ask ToddT about adding a hidden knob that effectively reverts the change at run-time.

2022-06-06 15:39 UTC, Todd-L-Miller commented
ToddT indicated that there should be a knob, and that it should default to the new behavior.

2022-07-29 19:39 UTC, JaimeFrey requested changes

2022-07-29 19:39 UTC, JaimeFrey commented on src/condor_daemon_client/daemon.cpp
> +		sinful.setAlias(host);
```suggestion
```
Deleting this call matches the logic in getDaemonInfo() when hostname:port is given. The call to New_alias() here should cause the given alias to be added to the sinful that's set in New_addr().

2022-08-08 19:13 UTC, JaimeFrey approved these changes
Looks good now.

2022-08-08 19:14 UTC, merged