HTCONDOR-740 - don't mess with user-held jobs
htcondor/htcondor pull request #660
Opened 2022-06-20 19:41 UTC by JaimeFrey

https://opensciencegrid.atlassian.net/browse/HTCONDOR-740

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2022-06-20 20:18 UTC, johnkn commented on src/condor_schedd.V6/schedd.cpp
> +		    hold_reason_code == CONDOR_HOLD_CODE::UserRequest ) {
do we need to knob this?

2022-06-20 20:32 UTC, JaimeFrey commented on src/condor_schedd.V6/schedd.cpp
> +		    hold_reason_code == CONDOR_HOLD_CODE::UserRequest ) {
I don't think we need a knob.

2022-06-20 21:43 UTC, johnkn requested changes
The changes to AnalyzePolicy need some more thought as to how release interacts with other policies.

2022-06-24 15:48 UTC, JaimeFrey commented
I fixed the issues identified by TJ and the unit tests. I also removed one redundant lookup of JobStatus when the schedd and gridmanager do periodic eval of all of their jobs.

2022-06-24 19:30 UTC, johnkn approved these changes
Looks good

2022-06-24 19:32 UTC, merged