HTCONDOR-1306-gridmanager-tidying
htcondor/htcondor pull request #832
Opened 2022-09-06 14:48 UTC by GregThain

https://opensciencegrid.atlassian.net/browse/HTCONDOR-1306

# HTCondor Pull Request Checklist for internal reviewers

- [ ] Verify that (GitHub thinks) the merge is clean. If it isn't, and you're confident you can resolve the conflicts, do so. Otherwise, send it back to the original developer.
- [ ] Verify that the related Jira ticket exists and has a target version number and that it is correct.
- [ ] Verify that the Jira ticket is in review status and is assigned to the reviewer.
- [ ] Verify that the Jira ticket (HTCONDOR-xxx) is mentioned at the beginning of the title. Edit it, if not
- [ ] Verify that the branch destination of the PR matches the target version of the ticket
- [ ] Check for correctness of change
- [ ] Check for regression test(s) of new features and bugfixes (if the feature doesn't require root)
- [ ] Check for documentation, if needed
- [ ] Check for version history, if needed
- [ ] Check BaTLab dashboard for successful build (https://batlab.chtc.wisc.edu/results/workspace.php) and test for either the PR or a workspace build by the developer that has the Jira ticket as a comment.
- [ ] Check that commit message references the Jira ticket (HTCONDOR-xxx)

## After the above
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional reviews)
- If the pull request is approved, take the ticket out of review state
- Assign JIRA Ticket back to the developer

2022-09-07 19:28 UTC, JaimeFrey requested changes
Fix sub-optimal variable names.

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				batch = m_batche;
```suggestion
		for (auto & next_batch : m_batches) {
			if ( next_batch->m_batch_name == batch_name ) {
				batch = next_batch;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +		for (auto & m_batche : m_batches) {
```suggestion
		for (auto & next_batch : m_batches) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				batch = m_batche;
```suggestion
			if ( next_batch->m_app_name == job->GetAppName() && next_batch->m_submit_status == BatchUnsubmitted ) {
				batch = next_batch;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			batch = m_batche;
```suggestion
	for (auto & next_batch : m_batches) {
		if ( next_batch->m_batch_name == job->remoteBatchName ) {
			batch = next_batch;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +	for (auto & m_batche : m_batches) {
```suggestion
	for (auto & batch : m_batches) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +		if ( m_batche->m_jobs.find( job ) == m_batche->m_jobs.end() ) {
```suggestion
		if ( batch->m_jobs.find( job ) == batch->m_jobs.end() ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +		if ( m_batche->m_jobs_done == m_batche->m_jobs ) {
```suggestion
		batch->m_jobs_done.insert( job );
		if ( batch->m_jobs_done == batch->m_jobs ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			if ( m_needFullQuery && !m_batche->m_need_full_query ) {
```suggestion
	for (auto & batch : m_batches) {
		if ( batch->m_submit_status == BatchSubmitted ||
			 batch->m_submit_status == BatchMaybeSubmitted ) {
			if ( m_needFullQuery && !batch->m_need_full_query ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			m_statusBatches.append( m_batche->m_batch_name.c_str() );
```suggestion
			m_statusBatches.append( batch->m_batch_name.c_str() );
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +					batch = m_batche;
```suggestion
			for (auto & next_batch : m_batches) {
				if ( next_batch->m_batch_name == ptr ) {
					batch = next_batch;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				 !m_batche->m_error_message.empty() ) {
```suggestion
		for (auto & next_batch : m_batches) {
			if ( next_batch->m_submit_status != BatchMaybeSubmitted ||
				 !next_batch->m_error_message.empty() ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				  job_itr != m_batche->m_jobs.end(); job_itr++ ) {
```suggestion
			next_batch->m_error_message = m_statusGahp->getErrorString();
			for ( set<BoincJob *>::iterator job_itr = next_batch->m_jobs.begin();
				  job_itr != next_batch->m_jobs.end(); job_itr++ ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				batch = m_batche;
```suggestion
		for (auto & next_batch : m_batches) {
			if ( next_batch->m_batch_name == batch_name ) {
				batch = next_batch;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +					m_job->SetEvaluateState();
```suggestion
				for (auto job : batch->m_jobs) {
					job->SetEvaluateState();
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				m_job->NewBoincState( m_job->remoteState.c_str() );
```suggestion
			for (auto job : batch->m_jobs) {
				job->NewBoincState( job->remoteState.c_str() );
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +	for (auto & m_batche : m_batches) {
```suggestion
	for (auto & batch : m_batches) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			 m_batche->m_submit_status == BatchFailed ) {
```suggestion
		if ( batch->m_submit_status == BatchMaybeSubmitted ||
			 batch->m_submit_status == BatchSubmitted ||
			 batch->m_submit_status == BatchFailed ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			if ( m_batche != m_activeSubmitBatch ) {
```suggestion
			if ( batch != m_activeSubmitBatch ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +		} else if ( !BatchReadyToSubmit( m_batche, &this_delay ) ) {
```suggestion
		} else if ( !BatchReadyToSubmit( batch, &this_delay ) ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +												 m_batche->m_jobs );
```suggestion
			int rc = m_submitGahp->boinc_submit( batch->m_batch_name.c_str(),
												 batch->m_jobs );
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				m_activeSubmitBatch = m_batche;
```suggestion
				batch->m_submit_status = BatchSubmitting;
				m_activeSubmitBatch = batch;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +												 m_batche->m_jobs );
```suggestion
			int rc = m_submitGahp->boinc_submit( batch->m_batch_name.c_str(),
												 batch->m_jobs );
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				m_batche->m_submit_status = BatchSubmitted;
```suggestion
				batch->m_submit_status = BatchSubmitted;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +						 m_batche->m_batch_name.c_str(),
```suggestion
						 batch->m_batch_name.c_str(),
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				m_batche->m_error_message = m_submitGahp->getErrorString();
```suggestion
				batch->m_submit_status = BatchFailed;
				batch->m_error_message = m_submitGahp->getErrorString();
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				  job != m_batche->m_jobs.end(); job++ ) {
```suggestion
			for ( set<BoincJob *>::iterator job = batch->m_jobs.begin();
				  job != batch->m_jobs.end(); job++ ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +	for (auto & m_batche : m_batches) {
```suggestion
	for (auto & batch : m_batches) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +		if ( m_batche->m_submit_status != BatchSubmitted ) {
```suggestion
		if ( batch->m_submit_status != BatchSubmitted ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +		if ( m_activeLeaseBatch != NULL && m_batche != m_activeLeaseBatch ) {
```suggestion
		if ( m_activeLeaseBatch != NULL && batch != m_activeLeaseBatch ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			time_t renew_time = m_batche->m_lease_time - ((2 * DEFAULT_LEASE_DURATION) / 3);
```suggestion
			time_t renew_time = batch->m_lease_time - ((2 * DEFAULT_LEASE_DURATION) / 3);
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +					unsigned this_delay = ( m_batche->m_last_lease_attempt + LEASE_RETRY_INTERVAL ) - now;
```suggestion
				if ( ( batch->m_last_lease_attempt + LEASE_RETRY_INTERVAL ) > now ) {
					unsigned this_delay = ( batch->m_last_lease_attempt + LEASE_RETRY_INTERVAL ) - now;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +				int rc = m_leaseGahp->boinc_set_lease( m_batche->m_batch_name.c_str(),
```suggestion
				int rc = m_leaseGahp->boinc_set_lease( batch->m_batch_name.c_str(),
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +					m_activeLeaseBatch = m_batche;
```suggestion
					m_activeLeaseBatch = batch;
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			int rc = m_leaseGahp->boinc_set_lease( m_batche->m_batch_name.c_str(),
```suggestion
			int rc = m_leaseGahp->boinc_set_lease( batch->m_batch_name.c_str(),
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +			m_batche->m_last_lease_attempt = time(NULL);
```suggestion
			batch->m_last_lease_attempt = time(NULL);
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +					  job != m_batche->m_jobs.end(); job++ ) {
```suggestion
				batch->m_lease_time = m_activeLeaseTime;
				for ( set<BoincJob *>::iterator job = batch->m_jobs.begin();
					  job != batch->m_jobs.end(); job++ ) {
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/boincresource.cpp
> +						 m_batche->m_batch_name.c_str(),
```suggestion
						 batch->m_batch_name.c_str(),
```

2022-09-07 19:28 UTC, JaimeFrey commented on src/condor_gridmanager/ec2-gahp-client.cpp
> +		arguments.emplace_back(i );
```suggestion
	for(const auto & item : v) {
		arguments.emplace_back(item );
```

2022-09-08 17:35 UTC, timtheisen commented
Wasn't boinc one of the things we were getting rid of?

2022-09-09 04:13 UTC, closed without merging

2022-09-09 04:14 UTC, GregThain commented
This branch has 30+ commits, most of which don't build, many of which are partial changes to variable names.  I'm closing this PR, and squashing all these commit into a different commit on a different branch and making a PR out of that.